CREATE VIEW NGUOI_DUNG AS SELECT 
QT_MA AS CN_MA,
QT_MA,
CN_TEN,CN_SDT,CN_EMAIL,
CN_NAM,CN_DIACHI,CN_TENTAIKHOAN,CN_MATKHAU,
CN_SALT,CN_ANHDAIDIEN,QT_NGAYNHANVIEC,
NULL AS TDG_MA 
    FROM QUAN_THU
UNION
SELECT 
DG_MA AS CN_MA,
NULL AS QT_MA,
CN_TEN,CN_SDT,CN_EMAIL,
CN_NAM,CN_DIACHI,CN_TENTAIKHOAN,CN_MATKHAU,
CN_SALT,CN_ANHDAIDIEN, NULL AS QT_NGAYNHANVIEC,
TDG_MA 
FROM DOC_GIA;

CREATE TRIGGER cap_nhat_dxn_ctm AFTER INSERT ON DON_XAC_NHAN
    FOR EACH ROW
    UPDATE CHI_TIET_MUON 
    SET CHI_TIET_MUON.DXN_MA=NEW.DXN_MA 
    WHERE 
        CHI_TIET_MUON.DS_MA=NEW.DS_MA 
        AND 
        CHI_TIET_MUON.PM_STT=NEW.PM_STT

        